"""add reset password fields

Revision ID: 27da4308290b
Revises: 6b13d336e826
Create Date: 2026-05-02 20:42:25.528871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27da4308290b'
down_revision = '6b13d336e826'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expire', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_expire')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
