"""image url added

Revision ID: 6b13d336e826
Revises: b95f2750e5bd
Create Date: 2026-05-01 22:02:15.047521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b13d336e826'
down_revision = 'b95f2750e5bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('users', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_url')
    op.alter_column('blogs', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
