"""add reset password fields

Revision ID: 98fb3c97b879
Revises: 27da4308290b
Create Date: 2026-05-02 20:52:26.582106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98fb3c97b879'
down_revision = '27da4308290b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
