"""add is_active to user

Revision ID: b95f2750e5bd
Revises: 5c4193ff3285
Create Date: 2026-04-20 09:51:56.650771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b95f2750e5bd'
down_revision = '5c4193ff3285'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
